### PR TITLE
Add functionality to exclude directorys matching a string from the index

### PR DESCRIPTION
**Pull request by Jon-Salmon**
I've added functionality to exclude directories from the search index.

The motivation behind this is I have lots of git repository lying around so needed a way to stop all the hidden files showing up in the index.

This adds and optional configuration option of 'excludeDirs' which can be set in the same way as the 'types' option. Any file or directory who's path contains any listed string will be excluded from the index.

This change required a re-write of the searching option to use the native python os.walk function.

I also took the opportunity to automatically update the catalogue whenever the config file is changed.

### CODE REVIEW

**Comment by EhsanKia** [comment]
Hmm, it would definitely make for much cleaner code is kpu.scan_direcotry could add support for exclusion filters. I'll see if I can convince them to add it.

In the meantime, it'd be cleaner anyway to replicate the scan_directory interface in a separate function (and implement it on top of os.walk), then use that inside the _load_dir function. Rather than having the whole algorithm in there.

Otherwise, this is a great idea. As long as it's backward compatible with Launchy configs, I'm all for new features.

**Comment by Jon-Salmon** [comment]
That would be much cleaner if it was integrated into the api, however it appears the dev is just keeping scan_directory for compatibility (http://keypirinha.com/api/module-util.html#keypirinha_util.scan_directory).

I agree it reads much cleaner as a separate function so I've moved it to that, and it's fully backwards compatibly with Launchy config as the extra configuration option added is optional, defaulting to no excludes.

**Comment by EhsanKia** [comment]
Thanks, one last small change. In python, you shouldn't use mutable data as default arguments:
http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/
Simply replace with with None, then in the code you can go `exclude = exclude or []`

**Comment by Jon-Salmon** [comment]
Ahh, thanks for pointing that out, I'd never realised python did that!

**Comment by EhsanKia** [comment]
Err, wasn't needed for the non-mutable data (0, and -1), but I'll take it :)

Cheers

**Pull request merged**
